import keyMirror from 'utils/keyMirror';

export const Styles = keyMirror(
    'Standard American Beer',
    'International Lager',
    'Czech Lager',
    'Pale Malty European Lager',
    'Pale Bitter European Beer',
    'Amber Malty European Lager',
    'Amber Bitter European Lager',
    'Dark European Lager',
    'Strong European Beer',
    'German Wheat Beer',
    'British Bitter',
    'Pale Commonwealth Beer',
    'Brown British Beer',
    'Scottish Ale',
    'Irish Beer',
    'Dark British Beer',
    'Strong British Ale',
    'Pale American Ale',
    'Amber and Brown American Beer',
    'American Porter and Stout',
    'IPA',
    'Strong American Ale',
    'European Sour Ale',
    'Belgian Ale',
    'Strong Belgian Ale',
    'Trappist Ale',
    'Historical Beer',
    'American Wild Ale',
    'Fruit Beer',
    'Spiced Beer',
    'Alternative Fermentables Beer',
    'Smoked Beer',
    'Wood Beer',
    'Specialty Beer',
    'Amber Hybrid Beer',
    'American Ale',
    'Belgian and French Ale',
    'Belgian Strong Ale',
    'English Brown Ale',
    'English Pale Ale',
    'India Pale Ale (IPA)',
    'German Wheat and Rye Beer',
    'Light Hybrid Beer',
    'Porter',
    'Scottish and Irish Ale',
    'Smoke Flavored/Wood-Aged Beer',
    'Sour Ale',
    'Stout',
    'Strong Ale',
    'Bock',
    'Dark Lager',
    'European Amber Lager',
    'Light Lager',
    'Pilsner',
    'Cider or Perry',
    'Mead',
    'Spice/Herb/Vegetable Beer'
);
