// import keyMirror from 'utils/keyMirror';

export const Styles = {
    '1A': 'Light American Lager',
    '1B': 'Standard American Lager',
    '1C': 'Premium American Lager',
    '1D': 'Munich Helles',
    '1E': 'Dortmunder Export',
    '2A': 'German Pilsner',
    '2B': 'Bohemian Pilsner',
    '2C': 'Classic American Pilsner',
    '3A': 'Vienna Lager',
    '3B': 'Oktoberfest/Marzen',
    '4A': 'Dark American Lager',
    '4B': 'Munich Dunkel',
    '4C': 'Schwarzbier (Black Beer)',
    '5A': 'Mailbock/Helles Bock',
    '5B': 'Traditional Bock',
    '5C': 'Doppelbock',
    '5D': 'Eisbock',
    '6A': 'Cream Ale',
    '6B': 'Blonde Ale',
    '6C': 'Kolsch',
    '6D': 'American Wheat or Rye',
    '7A': 'Northern German Altbier',
    '7B': 'California Common Beer',
    '7C': 'Dusseldorf Altbier',
    '8A': 'Standard Ordinary Bitter',
    '8B': 'Special/Best/Premium Bitter',
    '8C': 'Extra Special/Strong Bitter (English Pale Ale)',
    '9A': 'Scottish Light 60/-',
    '9B': 'Scottish Heavy 70/-',
    '9C': 'Scottish Export 80/-',
    '9D': 'Irish Red Ale',
    '9E': 'Strong Scotch Ale',
    '10A': 'American Pale Ale',
    '10B': 'American Amber Ale',
    '10C': 'American Brown Ale',
    '11A': 'Mild',
    '11B': 'Southern English Brown Ale',
    '11C': 'Northern English Brown Ale',
    '12A': 'Brown Porter',
    '12B': 'Robust Porter',
    '12C': 'Baltic Porter',
    '13A': 'Dry Stout',
    '13B': 'Sweet Stout',
    '13C': 'Oatmeal Stout',
    '13D': 'Foreign Extra Stout',
    '13E': 'American Stout',
    '13F': 'Imperial Stout',
    '14A': 'English IPA',
    '14B': 'American IPA',
    '14C': 'Imperial IPA',
    '15A': 'Weizen/Weissebier',
    '15B': 'Dunkelweizen',
    '15C': 'Weizenbock',
    '15D': 'Roggenbier (German Rye Beer)',
    '16A': 'Witbier',
    '16B': 'Belgian Pale Ale',
    '16C': 'Saison',
    '16D': 'Biere de Garde',
    '16E': 'Belgian Specialty Ale',
    '17A': 'Berliner Weiss',
    '17B': 'Flanders Red Ale',
    '17C': 'Flanders Brown Ale/Oud Bruin',
    '17D': 'Straight (Unblended) Lambic',
    '17E': 'Gueuze',
    '17F': 'Fruit Lambic',
    '18A': 'Belgian Blond Ale',
    '18B': 'Belgian Dubbel',
    '18C': 'Belgian Tripel',
    '18D': 'Belgian Golden Strong Ale',
    '18E': 'Belgian Dark Strong Ale',
    '19A': 'Old Ale',
    '19B': 'English Barleywine',
    '19C': 'American Barleywine',
    '20A': 'Fruit Beer',
    '21A': 'Spice/Herb/Vegetable Beer',
    '21B': 'Christmas/Winter Specialty SpiceBeer',
    '22A': 'Classic Rauchbier',
    '22B': 'Other Smoked Beer',
    '22C': 'Wood Aged Beer',
    '23A': 'Specialty Beer',
    '24A': 'Dry Mead',
    '24B': 'Semi-Sweet Mead',
    '24C': 'Sweet Mead',
    '25A': 'Cyser (Apple Melomel)',
    '25B': 'Pyment (Grape Melomel)',
    '25C': 'Other Fruit Melomel',
    '26A': 'Methelin',
    '26B': 'Braggot',
    '26C': 'Open Category Mead',
    '27A': 'Common Cider',
    '27B': 'English Cider',
    '27C': 'French Cider',
    '27D': 'Common Perry',
    '27E': 'Traditional Perry',
    '28A': 'New England Cider',
    '28B': 'Fruit Cider',
    '28C': 'Applewine',
    '28D': 'Other Specialty Cider Perry',
};
